spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    username: cfh00892977
    password: qweasd123
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: public
        format_sql: true
        generate_statistics: true
        jdbc:
          batch_size: 1
  h2:
    console:
      enabled: false
      path: /h2-console

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE
    org.springframework.transaction: TRACE

app:
  environment: UT

external:
  api:
    calculation:
      url: http://localhost:8081/api/v1/calculate
    document:
      url: http://mock-document-service/api/v1/upload
    gip:
      url: http://mock-gip-service/api/v1/tenant-mapping

# H2 数据库配置（已注释）
#spring:
#  datasource:
#    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
#    username: sa
#    password: 
#    driver-class-name: org.h2.Driver
#  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
#    hibernate:
#      ddl-auto: create-drop 